### ISSUE TITLE
shit is shit

### ISSUE THREAD

**Issue by 9pings** [Riot-Byte/aphrobyte-rat#5]
this shit dont work. dont call urself a developer when u cannot even fix shit

**Comment by Riot-Byte** [comment]
ur just a skid and cant set it up

**Comment by 9pings** [comment]
i asked you how many times, to show me how to set it up, you refused. and you dont even know what the word "skid" is pussio

**Comment by Riot-Byte** [comment]
skid

**Comment by 9pings** [comment]
shut up man, ur mother triplehooked your father nigga
